### ISSUE TITLE
Since my last update into geolocation module 0.9.4 my project doesn't work on mac/safari 4.0.4

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hugoloza/gwt-mobile-webkit#11]
```
http://sharemyposition.appspot.com

bodyhtml
/client/7A42A07EB3734AAC7E9D01B5021BDF7D.cache.html:709TypeError: Result of 
expression 
'(Id(),Hd).create' [undefined] is not a function.

it's working properly on my Firefox 3.5.7 and iPhone.
```

Original issue reported on code.google.com by `smaucourt` on 14 Jan 2010 at 1:20
